tool.paintertracer.name=Painter Tracer
tool.paintertracer.desc=Paint decals on surface from an entity
tool.paintertracer.left=Spawn a mobile painter entity
tool.paintertracer.right=Copy mobile painter settings

tool.paintertracer.control=Painter Control
tool.paintertracer.key=Force key
tool.paintertracer.key.tooltip=Press (if toggle is enabled) or hold the button to activate the force field
tool.paintertracer.toggle=Toggle forces
tool.paintertracer.starton=Apply forces on spawn

tool.paintertracer.parameters=Painter Parameters
tool.paintertracer.scale=Scale
tool.paintertracer.scale.tooltip=The decal size
tool.paintertracer.color=Color 
tool.paintertracer.rate=Interval 
tool.paintertracer.rate.tooltip=The time between each paint application 
tool.paintertracer.material=Material

tool.paintertracer.materials=Painter Materials
tool.paintertracer.texture=Decal